### ISSUE TITLE
`Video.completion` overrides `Curve.completion`

### ISSUE THREAD

**Issue by negative-seven** [motion-canvas/motion-canvas#1110]
**Describe the bug**
The `completion` method of `Video`, which relates to how much of the video has finished playing, overrides the unrelated `completion` method of `Curve`, which relates to how much of the curve is visible. This name collision seems to have unintentionally come up in https://github.com/motion-canvas/motion-canvas/commit/9810212648824b9a2fa2ecd6b597e3319d20b325. If I am wrong and this is in fact intentional, then there is the issue that the documentation for `Video.completion` is incorrectly inherited from `Curve.completion`.

**Comment by aarthificial** [comment]
Good catch! I don't want to change the way `completion` works since that would technically be a breaking change so a proper fix needs to wait until version 4 of Motion Canvas is ready.

For now, I added a new method to the `Video` node - `curveCompletion` that gives access to the actual stroke completion while the video completion remains the same. I also added clarification to the docs.
