### ISSUE TITLE
Improve rendering speed by not using .toDataUrl()

### ISSUE THREAD

**Issue by Specy** [motion-canvas/motion-canvas#1137]
**Description**
I was talking on the motion canvas discord about exporting frames at high speed to achive faster than 1x rendering, and it was brought up that the majority of time is spent in the [`.toDataUrl()`](https://github.com/motion-canvas/exporters/blob/f08e8e30d6bfb69da4b65d63c6acc3f209f98a4f/packages/ffmpeg/client/FFmpegExporterClient.ts#L90)converting the canvas to base64.

**Proposed solution**
There is a somewhat modern API available in most browsers that allows you to create videos frame by frame by getting a canvas/frame source which should be significantly faster than the data url export, look here:

https://github.com/w3c/mediacapture-record/issues/213

https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder

https://github.com/Vanilagy/webm-muxer

**Comment by aarthificial** [comment]
The next release `3.18` no longer uses `toDataUrl` for exporting and instead passes raw canvas data directly to ffmpeg which is as fast is it can get (#1095)

Exporting in Motion Canvas is handled by plugins - there's a built-in image sequence exporter and a standalone ffmpeg exporter. If you'd like to use WebCodecs I'd recommend creating your own exporter since it doesn't really make sense to modify the ffmpeg exporter so that it doesn't use ffmpeg.

**Comment by Specy** [comment]
Yes i made the issue more like a suggestion of possible ways to speed up export in case that the api was not known.

Should i close this issue?

**Comment by aarthificial** [comment]
Yes, I think we can close it then
