### ISSUE TITLE
visual bug with Rect

### ISSUE THREAD

**Issue by derpmagician** [motion-canvas/motion-canvas#207]
**Describe the bug**
if your Rect object has a radious of 30 or bellow and the size is less than 60 it will show deformed even if you scale it bigger
https://i.imgur.com/ycimoVB.gif

```ts
export default makeScene2D(function* (view) {

  const header = createRef<Rect>();
  view.add(
    <Rect
      ref={header}
      position={[0,0]}
      size={[50,50]}
      fill="ffffff"
      radius={30}
    />,
  );

  yield* all(

    header().scale.x(1, 1).to(5, 1).to(1, 1),
    header().scale.y(1, 1).to(5, 1).to(1, 1),
  );
```

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Console errors**
If applicable, add a screenshot of the errors displayed in the console of your browser (F12) or your terminal.

**Package versions (please complete the following information):**

- core: [e.g. 1.0.0]
- ui: [e.g. 1.0.0]

**Comment by aarthificial** [comment]
Changing the scale doesn't help because the radius is scaled together with the object.

This is a weird implementation quirk caused by the fact that we support overflowing corner radiuses, for example:
```tsx
<Rect
  ref={header}
  position={[0, 0]}
  size={[50, 50]}
  fill="ffffff"
  radius={[40, 10, 10, 10]}
/>
```
![image](https://user-images.githubusercontent.com/64662184/216882935-36869ac4-920c-478d-838b-3b195259ee37.png)

A temporary solution for you would be to use `25` for the radius (half the width of your rect: `50 / 2 = 25`)
But I'll check if the implementation can be improved to fix this.
