### ISSUE TITLE
Interactive live presentation support

### ISSUE THREAD

**Issue by TheZoq2** [motion-canvas/motion-canvas#213]
**Description**
Motion canvas looks super interesting to me, but most of my presentations are live rather than pre-recorded video. I think the tool might be very useful there too, given a small amount of extra features.

**Proposed solution**
As I understand it, animations in motion canvas can currently be triggered by a specific pre-set (but editable in the editor) events. Would it be possible to have those events triggered instead by a key press? That way, it would work more like a traditional power-point presentation.

**Additional context**
I've only looked at the intro videos for this, so I have no idea if it is viable, or desirable. Feel free to ignore if this is out of scope!

**Comment by aarthificial** [comment]
This idea has been brought up a lot during early access and I completely support it.
It would have to be implemented separately from time events though (their name is a bit misleading, they don't really trigger anything) but it's completely viable.

**Comment by carsonoid** [comment]
+1 on this. In the past I have used [Sozi](https://sozi.baierouge.fr/) for diagram heavy presentations. It works really well. But I think that Motion Canvas would be a really useful tool to have at my disposal as well for certain kinds of presentations.

**Comment by Tandashi** [comment]
+1 on this from me as well. Was already thinking of implementing this for myself, but seeing that @aarthificial is also on-board with this is awesome to see.

## Proposal
Not sure what the plans are for implementing this, but would propose a few things if I may:
- create a generic way for different event types to be flexible in the future
- allow event to execute functions / a callback
- create a track in the editor per event type

In the following paragraphs, I'll go into why I think those points are important to consider.
(Please keep in mind that I am still fairly new to this framework and wasn't yet able to deep-dive into every aspect of the framework)

### Generic Events & Events executing callbacks
These kind of go hand in hand. Allowing Events to execute a callback function would allow for a variety of event-types being created without having to change the core of the Event System. 

### Tracks per Event type
Creating multiple events for all kinds of different things can quickly get quite confusing and one loses track easily.
Separating these kinds of events by type and giving each type a single `track` in the editor might help with this.

**Example**:
![Timeline multi-event](https://user-images.githubusercontent.com/18377875/217102463-8738ac0e-119e-4306-87f3-337465b36cbc.png)

**Comment by Tandashi** [comment]
Firstly, love the idea of not just pausing the animation, but pause the generator instead. Haven't thought about this, but I like it. Especially because it allows for background animations to be played, as you said.

---

> Can you provide some examples of the API you have in mind? Who would declare the callback, who would dispatch it, based on what, etc?

Have been thinking about the callbacks for a day and a half now. I couldn't really come up with a good example that could really benefit from what I had in mind. Still wanted to outline my initial idea, though. Essentially, it just was a `'wrapper'`/`utility function` that does what you described in a single step, rather in multiple.

For example, one sometimes wants to cancel a task or set a new offset. Both things that don't generate, but are needed once occasionally.

```ts
yield* waitUntil('event');
cancel(task);

// Would be come
yield* withCallback(waitUntil('event'), () => cancel(task));
```

But as I said, after thinking about is for more than 2 min it's quite useless and has no benefit at all.

---

> I'm against trying to abstract this together with time events. Again, time events represent a number editable through the editor ('time event' as in 'an event in time' - nothing to do with the programming concept of event dispatchers, etc).
Slide Pauses should be implemented separately from that.

Can totally understand what you mean, and I get that you don't want to mix the concept of event dispatching with the concept of time events. However, I think it would be useful to have some sort of time events that don't have a `duration`.
These could be used to create a point in the animation to specify a time point rather than a 'span'.

This however would just be a convenience thing, so one doesn't have a blue tray behind the event when adjusting the position (if that makes sense).

**Comment by gmli** [comment]
I would like to use Motion Canvas in my company to explain technical stuff to my colleagues live, so this feature would be really nice.

Thinking of how my electronic music gear work, I not leaning towards a "slide" concept at all. What would allows me to have maximum freedom while presenting would be those actions :  

- play indefinitely (until a stop action)
- play to the end of the next animation
- stop immediately 
- stop right at the end of the currently playing animation

Hope this could help…

**Comment by Tandashi** [comment]
I think that is an interesting concept to take a look at.
I am assuming that you want to have a more dynamic way to present rather than a static way
(judging by `play indefinitely (until a stop action)`).

Regardless, just to make sure:
<details>
  <summary><b>Static way with the proposed `waitForSlide` generator function</b></summary>

> play to the end of the next animation
```tsx
// current animation
yield * circle().fill('#fff', 1)
// next animation
yield * circle().fill('#f0f', 1)
yield * waitForSlide(...)
```
---

> stop immediately
```tsx
yield * waitForSlide(...)
```
---

> stop right at the end of the currently playing animation
```tsx
// current animation
yield * circle().fill('#fff', 1)
yield * waitForSlide(...)
```
</details>

**Attention personal opinion**:
The first thing that comes to mind when thinking about this approach would be the need for some sort of event system (like real events, not `time events`). Different events would be emitted depending on the action. **Personally** I feel that if this approach would need a whole new event system behind it to achieve this, it would move more into the direction of a proper presentation software and away from the core concept of Motion Canvas. The `waitForSlide` generator function seems to be, **at least for me**, be a good compromise since it fits perfectly into the concept of having a lot of generator functions to design an animation.

**Comment by aarthificial** [comment]
> Is there really a need to register a slide? (currently can't see a reason why this is necessary)

I'm assuming the presenter may want to go back to the previous breakpoint or fast forward to the next one. For that, we need a registry that can give us the previous/next pause for any given pause.

> What sets project.isPresenting? I assume the editor when some presentation mode is toggled?

Yes.

**Comment by Tandashi** [comment]
If we stick to the `waitForSlide` approach would love to claim this if you don't mind :)

**Comment by aarthificial** [comment]
Thanks, but I'll have to claim this issue for myself. I'm currently working on #166 which requires some major changes to the architecture of playback and I'd like to account for the presentation mode as well.

**Comment by Aurora2500** [comment]
One thing I wanted to add to this is that for it to be used for presentations it would be fairly important to be able go back between "slides". Say you missclick before you intended to and the animation plays before you gave your explanation, or if there is a question from the crowd about something that happened a couple slides back.

**Comment by David-Kunz** [comment]
It would also be great to have a 'static' mode. At the end of a presentation, people usually ask questions and you want to navigate to a certain slide for the final state (no animations).

**Comment by PfisterFactor** [comment]
Not sure if this issue would be the place to make this comment.

I think the concept of "slides" would work for this, but I just wanna put out my usecase so that maybe a more general solution could be thought of with this.

I want to implement something like a live audio visualizer that changes the heights of different frequency band rectangles depending on incoming audio.

For this you would need:
- A way to make animations run indefinitely
- A way to have events sent to the animation system (i.e. the volume of the frequency band) and react dynamically to them

**Comment by tomByrer** [comment]
Why not use markers on the timeline to signify where each 'slide' would be?

**Comment by TheZoq2** [comment]
That was much quicker than I expected, nice job :heart: Now I just need to find an excuse to make a presentation :D

**Comment by JayKay135** [comment]
@aarthificial Where can I find the source code for this presentation mode example?

**Comment by Tandashi** [comment]
@JayKay135 Should be this one: https://github.com/motion-canvas/motion-canvas/blob/main/packages/examples/src/scenes/presentation.tsx if I am not mistaken

**Comment by JayKay135** [comment]
@Tandashi Thank you very much
