### ISSUE TITLE
Text fontSize property can't be updated

### ISSUE THREAD

**Issue by jacksontriffon** [motion-canvas/motion-canvas#246]
When trying to update the fontSize motion-canvas freezes.

**To reproduce:**
- Create a text element and update it's fontSize in a `yield* all(...)` such as:
```ts
yield* all(
    ..., 
    Text().fontSize(24, 1)
)
``` 

**Expected behavior**
The fontSize will update like other properties such as Size, Position, etc...

**Console errors**
> Cannot use 'in' operator to search for 'lerp' in null

**Package versions**
> Core: v2.0.0
> UI: v2.0.0

**Comment by jacksontriffon** [comment]
As a workaround to anyone stuck, the `Text.scale()` property works just as expected

**Comment by exdeejay** [comment]
I'm taking a look at this one. `fontSize` is initialized to `null` so that it can properly inherit the font size of its parent in layout mode, so it's not as simple as setting a default font size number (unless the inheritance of font size in layout mode is unwanted behavior). I'm thinking of making a custom decorator for inherited values that returns the computed value in uninitialized cases but also allows for custom values. This is also tied to #243 in that the initial value of `null` for `fontSize` is causing an error.

**Comment by exdeejay** [comment]
`customX` and `customY` seem to be the solution for this in regards to positioning, but it would be a hassle to create a computed method, getters, setters, and a custom signal for each property that can possibly be calculated through the browser, so a different solution is most likely necessary here.

**Comment by chris-findlay** [comment]
An uninitialised value that is inherited feels like it should lerp like this:
`t => (prop.value() ?? prop.getInheritedValue()) * (1-t) + (newValue ?? prop.getInheritedValue()) * t`

**Comment by chris-findlay** [comment]
That would also support tweening against a currently-animating inherited valve too.
