### ISSUE TITLE
Allow logging of non-string values

### ISSUE THREAD

**Issue by ksassnowski** [motion-canvas/motion-canvas#267]
**Description**

Currently, the logger only accepts a parameter of type `string | LogPayload`. I personally use the logger mostly when trying to debug a wonky animation. In these cases, I will almost always want to log complex types like `Vector2` or `Rect`s. What I need to do in these cases is to manually `JSON.stringify` the payload before passing it to the logger. 

```ts
const logger = useLogger();
logger.debug(JSON.stringify(rect().cacheRect());
``` 

While this is not a huge deal, it's starting to become death by a thousand paper cuts.

**Proposed solution**

Allow the logger to also accept non-string values and call `JSON.stringify` on them internally. 

```ts
const logger = useLogger();

// Would call `JSON.stringify` on the input internally
logger.debug(rect().cacheRect());
```

The big problem here is what the new method signature of these methods should become. Since we would essentially be widening the type to `any`, we'd lose the ability to distinguish between `LogPayload`s and any other payload.

**Comment by aarthificial** [comment]
Technically, you can do
```ts
logger.debug({object: rect().cacheRect()});
```
This will do the parsing for you and display it nicely in the console.
But it could be nice to have some shortcut method to do this.

Ideally, it wouldn't be a part of the logger, because its API was designed to be compatible with other loggers out there, such as [winston](https://github.com/winstonjs/winston)
Maybe some simple function like `debug()` that would do the whole `useLogger`, `{object: ...}` stuff?

**Comment by ksassnowski** [comment]
I could live with a function like that. Should I open a PR for this? Where should this function live, ideally? I assume somewhere in `@core/utils`?
