### ISSUE TITLE
Functions starting with `create` vs functions starting with `make`

### ISSUE THREAD

**Issue by revosw** [motion-canvas/motion-canvas#268]
(not really a bug, and not really about documentation, and not really a new feature request...)
**Description**
Currently, there are functions that start with `make___()` and `create___()`
https://github.com/motion-canvas/motion-canvas/search?q=%22create%22
https://github.com/motion-canvas/motion-canvas/search?q=%22make%22

Was choosing the `make` prefix deliberate? Or would it be desired to rename them to `createProject`, `createRef` and so on for consistency?

**Comment by aarthificial** [comment]
I agree the name choice may not be the best. My general reasoning was that `make` turns something into another thing (as in "make it into something"), while `create` creates something new out of nothing.

**Comment by aarthificial** [comment]
I'm open to better suggestions of course.

**Comment by Tandashi** [comment]
Just me 5 cents on this: Personally I think both are valid and I don't have a personal preference. However wouldn't a name clash occur when renaming all the `make___` to `create___`? Since there exists a `createRef` and a `makeRef`, we would need to find a new name for `makeRef` at least. Just something to keep in mind.

**Comment by revosw** [comment]
Ah, I didn't catch that there's _both_ a createRef and makeRef, then that ends this discussion pretty quickly
