### ISSUE TITLE
Video doesn't pause in the player, when pressing spacebar while the play/pause button is :active

### ISSUE THREAD

**Issue by tcardel** [motion-canvas/motion-canvas#273]
If I have already clicked the pause button and then use the spacebar instead, it neutralizes the pause, since it gets triggered twice.

**Comment by aarthificial** [comment]
Is mostly likely caused by the button being focused after pressing this.
An easy way to fix this would be to do `preventDefault` when activating the play button using the spacebar.

**Comment by miikkuu** [comment]
Hello @aarthificial  New to contributions. Can you guide me how to solve this issue?

**Comment by aarthificial** [comment]
Hi @miikkuu, you need to start by setting up the project locally and running the `ui` package, this process is described in the [README](https://github.com/motion-canvas/motion-canvas#developing-ui). Once you have it up and running, you can find the play button that's causing this issue here:
https://github.com/motion-canvas/motion-canvas/blob/b8708732af0fc08d9ff9eeecbbb77d65f1b36eb8/packages/ui/src/components/playback/PlaybackControls.tsx#L90-L96
In case of any problems, feel free to join [our Discord server](https://discord.gg/XnnWTrHYAW) and ask for help over there

**Comment by aarthificial** [comment]
Closed by #299
