### ISSUE TITLE
Opacity transition causes clipping of Text node

### ISSUE THREAD

**Issue by flocto** [motion-canvas/motion-canvas#290]
**Describe the bug**
When opacity transitions to 1, text inside Text nodes will clip downwards for no specific reason.
Also when opacity is at 1 and starts transitioning the text will clip upwards.

**To Reproduce**
```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { Text } from '@motion-canvas/2d/lib/components';
import { createRef } from '@motion-canvas/core/lib/utils';
import { waitFor } from '@motion-canvas/core/lib/flow';


export default makeScene2D(function* (view) {
    const txt = createRef<Text>();
    view.add(
        <Text
            ref={txt}
            fill="white"
            opacity={0}
            text="Test Text"
        />
    );

    yield* waitFor(1);
    yield* txt().opacity(1, 1);
    yield* waitFor(1);
    yield* txt().opacity(0, 1);
    yield* waitFor(1);
});
```

**Expected behavior**
The text should just fade in normally and not clip down/up.

**Console errors**
No errors anywhere.

**Package versions (please complete the following information):**

- core: 2.1.0
- ui: 2.1.0

**Additional context**
I'm not even sure what's causing this, could be something specific to me but inspection of the Text node through the UI shows that the only value of the node that changes between the frames of it clipping up/down is the opacity.

**Comment by aarthificial** [comment]
The example you provided seems to be working fine:
![image](https://user-images.githubusercontent.com/64662184/218004727-7e558e7d-dafd-4cf6-85b9-51e81b4f4b55.png)
If you change the font size to something bigger, the clipping will occur, which I'm assuming is what you're experiencing:
![image](https://user-images.githubusercontent.com/64662184/218004817-0d6b4c7f-8e1a-4f1c-b663-9ed11400e02e.png)
In this case, this is caused by the `lineHeight` being too small, setting it to something bigger than the `fontSize` should fix the issue.
We're working on making the `lineHeight` scale properly with the `fontSize`: #238

**Comment by flocto** [comment]
Hmm, I npm updated just to check if that was the issue and it seems to have resolved it anyway.
The example I provided (and what I was doing before) both stopped clipping.

Closing issue then.
