### ISSUE TITLE
GitHub Sponsors & Starchart

### ISSUE THREAD

**Issue by Pebaz** [motion-canvas/motion-canvas#307]
Dude you've got to setup GitHub Sponsors on this repo. You've created something that is better than the competition, for free, but people still want to donate money. Right now, you're at 6.1k stars on GitHub. Since usually only 1% of your audience will convert/donate/buy/purchase, you're looking at roughly 61 people who would give you money for your free(!) product.

Also, I'd suggest putting this on your repo, it's nuts to see how popular this got so fast! Congratulations man, this is really exciting to see. You can view it at: https://starchart.cc/motion-canvas/motion-canvas

[![Stargazers over time](https://starchart.cc/motion-canvas/motion-canvas.svg)](https://starchart.cc/motion-canvas/motion-canvas)

**Comment by ksassnowski** [comment]
Just FYI, he has a [Patreon](https://www.patreon.com/aarthificial), which AFAIK could actually be linked to from GitHub's sponsor tab.

**Comment by aarthificial** [comment]
Thanks! For now, I configured the funding for my own Patreon/GitHub. 
Once we have some more maintainers, etc. we'll configure the funding for the organization as a whole.

I don't really want to brag about the popularity of the project since it's mostly undeserved and made possible by my reach as a youtuber. It would feel unfair toward other open-source projects.
