### ISSUE TITLE
CodeBlock component isn't exported

### ISSUE THREAD

**Issue by DrNightmare** [motion-canvas/motion-canvas#322]
**Describe the bug**
The `CodeBlock` component isn't exported in [`@motion-canvas/2d/src/components/index.ts`](https://github.com/motion-canvas/motion-canvas/blob/main/packages/2d/src/components/index.ts). Is this intentional?

**To Reproduce**
Attempt to import the CodeBlock component:
`import { CodeBlock } from "@motion-canvas/2d/lib/components";`

**Expected behavior**
The component is successfully imported.

**Console errors**
![image](https://user-images.githubusercontent.com/8812382/218300173-5cf59cfa-8217-4a30-8f06-c3fd536be3b4.png)

Text form of above error:
`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@motion-canvas_2d_lib_components.js?v=c5be1f43' does not provide an export named 'CodeBlock'`

**Package versions:**
- `@motion-canvas/2d: ^2.3.0`

**Comment by Ross-Esmond** [comment]
This was intentional. I bundled **all** the languages into code-fns to keep things simple, which is a lot. It bumped the size of MC by an order of magnitude, and it wasn't removed by tree shaking. We either need to get tree shaking working or I need to get lazy loading of languages working.

This is a good issue to have up though. If anyone knows how to fix tree shaking I would appreciate it.

**Comment by aarthificial** [comment]
@Ross-Esmond since fixing three-shaking may be a bit of a problem (thank you decorators /s), maybe we could make the starry night instance injectable through the `parse` method? This would allow us to do the initialization in the `CodeBlock`, which knows precisely what languages are needed. From the perspective of users, nothing would change.

**Comment by Ross-Esmond** [comment]
I thought about it. That would make parse async, which I think would require the language and code signals to be async, rather than just the view add. Can MC have an async signal setter? Alternatively, can components trigger an await at uncertain times during the render? I know you can during a thread, but if someone changes code without a duration, is that possible? @aarthificial

**Comment by aarthificial** [comment]
Yes, we have support for async signals and during rendering, we wait for any encountered Promises:
https://github.com/motion-canvas/motion-canvas/blob/d5c5a1bfcd6a257f296b256ef6ad34f401829089/packages/core/src/scenes/GeneratorScene.ts#L147-L157
But I thought about passing an already awaited StarryNight, the thing that's currently called `starryNightCache` in the code.
This way, the only async operation would be:
- creating the `CodeBlock` (like it is right now)
- changing the language during animation

**Comment by aarthificial** [comment]
Closed by #401
