### ISSUE TITLE
Update Discord Link

### ISSUE THREAD

**Issue by whokilleddb** [motion-canvas/motion-canvas#333]
The Discord Link in [README.md](https://github.com/motion-canvas/motion-canvas/blob/main/README.md)  has expired and doesn't let new people join in onto discord to discuss ideas 😢

**Comment by pklaschka** [comment]
I don't want to claim this issue since it should be up to the maintainers how to handle this (since, e.g., adding a permanent link can come with disadvantages in terms of spam). But until there's a solution, the server let me create an invite link that will expire in 7 days (which I hope I can post here without anyone having a problem with it), so until this is fixed, here you go:

https://discord.gg/qTf3VfgZ

**Comment by whokilleddb** [comment]
Thanks @pklaschka , but turns out the original also works, just not from the browser, but seems to work alright when accessed from mobile. Sorry for the trouble!

**Comment by pklaschka** [comment]
Even better, and no worries!

**Comment by aarthificial** [comment]
I just wanted to add that the link in the README and on the webpage, as it is right now, should be permanent
