### ISSUE TITLE
Some of ShapeProps attributes not supporting signals.

### ISSUE THREAD

**Issue by alirezaopmc** [motion-canvas/motion-canvas#350]
Salam. (Hello in persian)
I investigated the error AlphaTech was experiencing to find this problem.

---
## Code
```ts
const props = {
    lineCap: 'round',
};

<Line {...props} />
```

---
## Error
```
Type '{ lineCap: string; }' is not assignable to type 'LineProps'.
    Types of property 'lineCap' are incompatible.
```

---
## Description
As you can check the source code [here](https://github.com/motion-canvas/motion-canvas/blob/3b33d73416541d491b633bada29f085f5489f6c2/packages/2d/src/components/Shape.ts#L18)] there is a difference between the `fill` property and the `lineCap` one.

```ts
export interface ShapeProps extends LayoutProps {
  fill?: SignalValue<PossibleCanvasStyle>;
  ...
  lineCap?: SignalValue<CanvasLineCap>;
  ...
}
```

As I checked more deeply I figured out that the typing is different. To let developers use Signals or such values like `lineCap` which only has three possible values. Between `CanvasLineCap` and the actual type of `lineCap`, there must be further typing levels. It has to be something like `PossibleCanvasLineCap`, I suppose.:
```ts
type PossibleCanvasLineCap = string | CanvasLineCap
```
---
P.S:
Since this is my first actual issue with an active GitHub repository. I would be grateful for any advice you could provide me to start tackling this problem. Due of the possibility of discovering other elements and attributes having the same issue, I will mention other components with the same problem later.

**Comment by ksassnowski** [comment]
This isn't really a problem with Motion Canvas but with how Typescript handles checking enums. 

The reason you're getting this error is because the type that Typescript has inferred for the `lineCap` property on the `props` object is `string`. And because `string` isn't a subset of `CanvasLineCap`, there's a type mismatch. It doesn't matter that the actual _value_ of `lineCap` happens to be one of the allowed values. From Typescript's point of view, this could be any string.

There are two ways to fix this in userland, both revolve around making sure that Typescript understands the actual type of `props.lineCap`:

1. Type the entire `props` object to be of type `ShapeProps` or `LineProps`

```ts
const props: LineProps = {
  // Since `props` is now typed as `LineProps`, Typescript knows that
  // `lineCap` *must* be a valid `CanvasLineCap` value.
  lineCap: "round",
};

<Line {...props} />
```

2. Use a type cast for `lineCap`

```ts
const props: LineProps = {
  lineCap: "round" as CanvasLineCap,
};


<Line {...props} />
```

I would go for option 1 as option 2 would still allow you to use a random value for `lineCap` since Typescript will always trust your typecast.

Widening the type definition for the `lineCap` property is not a good idea as that would allow any string to be set even though there are only three valid options.

**Comment by alirezaopmc** [comment]
Alright. How about `fill`?
```ts
<Line
    fill={'not-a-color'}
/>```

This doesn't raise an error.
