### ISSUE TITLE
Alternative renders(gif, webm, mp4) support

### ISSUE THREAD

**Issue by gut4** [motion-canvas/motion-canvas#364]
It will be very useful to have a support for an alternative renders.

For example, full client side renders(gif, webm, mp4) like in https://github.com/tapioca24/p5.capture

Also I think it's possible to create performant & high quality render with ```offscreenCanvas``` & ```webcodecs``` APIs
Browser support looks good (Safari start to support this APIs)
https://caniuse.com/webcodecs
https://caniuse.com/offscreencanvas

**Comment by aarthificial** [comment]
I'm not sure how `OffscreenCanvas` would increase the rendering performance. Animation can't happen in a separate thread because Layouts require access to the DOM. But even if we could do that (by switching to Yoga, for example) just off-putting the work to another thread won't speed it up, we'd need a way to distribute the workload across multiple threads to see any gains. I'm happy to be proven wrong, of course. Furthermore, the bottleneck of the current pipeline is not animation/rendering but rather storing the output data.

When it comes to WebCodes, I initially wanted to use them for rendering, but there were two problems:
- They can only encode video chunks, you still need a remuxer to produce a complete mp4 video.
- The resulting quality was really bad. I spent some time trying different settings and could not come up with anything satisfying. Again, happy to be proven wrong here.

The idea of more export options is as old as this repo (#4). I'm currently working on a major rewrite of the playback architecture which, among other things, will make the rendering process separate from the preview and allow for more customization there. I'd like to go for a plugin architecture, where custom exporters can be installed as needed.

I also think we should play to our strengths, and instead of going for client-side renderers, use the server side of Motion Canvas. This would give us the full potential of FFmpeg, for example.

**Comment by mohsinhijazee** [comment]
This might be interesting, not sure if relevant or applicable: https://github.com/ffmpegwasm/ffmpeg.wasm

**Comment by aarthificial** [comment]
The FFmpeg exporter is now available as a standalone plugin:
https://github.com/motion-canvas/exporters#installation
