### ISSUE TITLE
Ability to change background color from within the scenes

### ISSUE THREAD

**Issue by AuricX** [motion-canvas/motion-canvas#367]
I request the ability to be able to change the background color of the main project from within the scene, using the Tweening methods and whatnot instead of having to rely on big rectangles OVER the background.

Example Below:
![image](https://user-images.githubusercontent.com/94857960/219802815-5aa646f2-094a-4b62-863b-864985a28b77.png)

**Comment by aarthificial** [comment]
`Project` is a persistent class that doesn't get reset the way the view does. 
Making `background` a signal would create a memory leak, where old dependencies from disposed-of views would aggregate over time. 

My proposition is to simply make `View2D` extend `Rect` so that it's possible to do:
```ts
yield* view.fill('black', 1);
```

Also, `useProject` will be removed in `v3.0.0`. It's an internal helper that shouldn't be accessed by users.

**Comment by strau0106** [comment]
I'll be working on this Isssue
