### ISSUE TITLE
Add configuration option to allow JSX syntax to be used in ".js"-files

### ISSUE THREAD

**Issue by BlenderDefender** [motion-canvas/motion-canvas#445]
**Description**
Currently, trying to use JSX syntax inside of ".js"-files results in the following error:
```bash
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax.
If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: F:/my-motion-canvas-project/src/scenes/example.js:37:20
  36 |          // selection={word(0, 0, 5)}
  37 |        ></CodeBlock>
                          ^
```
Due to issues with VSCode autocompletions for ".jsx"-files, I need to name my file "*.js".

**Proposed solution**
I'd suggest adding a configuration option that makes it possible to allow JSX-Syntax inside of ".js"-files.

**Comment by gmile** [comment]
Hi, @BlenderDefender!

Adding to what @aarthificial said, it looks like using JSX in `.js` is a common issue that must be resolved using `vite` config, and many other are looking for answers at the moment. There's a discussion at Vite repo about this, but there doesn't seem to be a clean answer: some people claim to have found "holy grail" of the config to make this work, only to be later refuted by someone else.

Here's a link to that discussion: https://github.com/vitejs/vite/discussions/3448. This answer from 2 weeks ago seams most clean, you might have some luck if you start with trying it: https://github.com/vitejs/vite/discussions/3448#discussioncomment-5386027

For what it's worth, I would say this issue is out of scope for motion-canvas issue tracker, though.

**Comment by BlenderDefender** [comment]
@gmile Thank you
