### ISSUE TITLE
Line start/end issues with radius

### ISSUE THREAD

**Issue by cyberalien** [motion-canvas/motion-canvas#472]
**Describe the bug**
Weird animation is happening when line has radius and animation happens near middle point.

Screenshot of line that supposed to render something like `>` with `start=0.45`:
![000000](https://user-images.githubusercontent.com/822287/222886075-c797acca-29dc-4e63-9909-ade763c2878e.png)

**To Reproduce**
Code sample below.

Bug happens when `start` is between 0.40 and 0.50.

```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { Line } from '@motion-canvas/2d/lib/components';
import { waitFor } from '@motion-canvas/core/lib/flow';
import { createRef } from '@motion-canvas/core/lib/utils';
import { linear } from '@motion-canvas/core/lib/tweening';

export default makeScene2D(function* (view) {
	const ref = createRef<Line>();
	view.add(
		<>
			<Line
				ref={ref}
				stroke="#800"
				lineWidth={80}
				radius={4}
				start={0.45}
				points={[
					[-200, -120],
					[-80, 0],
					[-200, 120],
				]}
			/>
		</>
	);

	// yield ref().start(1);
	// yield* ref().start(0, 2, linear);
});
```

**Expected behavior**
Expected not to see cut out from previously rendered line.

**Package versions (please complete the following information):**

- core: 3.0.0
- ui: 3.0.1

**Comment by aarthificial** [comment]
There's not much we can do about this since this is how the [`arc`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc) method draws the lines:
```ts
context.moveTo(50, 100);
context.arc(100, 110, 10, -Math.PI / 2, -Math.PI / 4);
context.lineWidth = 80;
context.lineJoin = 'round';
context.strokeStyle = 'black';
context.stroke();
```
<img src="https://user-images.githubusercontent.com/64662184/222925288-2872360d-ae32-4da2-8ac5-be485d058548.png"  width="240">

Since the `lineWidth` to `radius` ratio in your example is really high, you can try using `lineJoin={'round'}` instead of `radius` for a better effect.

**Comment by cyberalien** [comment]
Thanks a lot for explanation!
