### ISSUE TITLE
Letter spacing is applied after last letter

### ISSUE THREAD

**Issue by cyberalien** [motion-canvas/motion-canvas#528]
**Describe the bug**
When using `letterSpacing` in text, it is added after last letter.

**To Reproduce**
Code snippet:
```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { Node, Rect, Txt } from '@motion-canvas/2d/lib/components';
import { createRef } from '@motion-canvas/core/lib/utils';

export default makeScene2D(function* (view) {
	const rectRef = createRef<Rect>();
	const txtRef = createRef<Txt>();
	view.add(
		<Node>
			<Rect width={1920} height={1080} fill="#888" />
			<Rect ref={rectRef} width={1920} height={1080} fill="#024" />
			<Txt
				ref={txtRef}
				text="TEXT"
				fontWeight={400}
				fontSize={256}
				fill="#FFF"
				letterSpacing={64}
			/>
		</Node>
	);

	rectRef().width(txtRef().width());
	rectRef().height(txtRef().height());
});

```

Screenshots with and without `letterSpacing`, using rectangle to show text bounding box:

![normal](https://user-images.githubusercontent.com/822287/225325767-d1d8b490-4a0b-4368-9c1d-22a9abb5d800.png)
![bug](https://user-images.githubusercontent.com/822287/225325794-36ba71ff-2d86-4379-a77a-7c7029f235a9.png)

**Expected behavior**
Expected spacing to be applied only between letters.

**Package versions (please complete the following information):**

- core: 3.2.0
- ui: 3.2.1

**Comment by aarthificial** [comment]
I'm not sure if we should fix that since that's how the [letter-spacing](https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing#examples) property in CSS works:

![image](https://user-images.githubusercontent.com/64662184/225356014-19e85653-2358-4098-83d0-d7c741bc44f4.png)

You can easily counteract this with `layout` and `marginRight`:
```tsx
<Node>
  <Rect width={1920} height={1080} fill="#888" />
  <Rect ref={rectRef} layout fill="#024">
    <Txt
      ref={txtRef}
      text="TEXT"
      fontWeight={400}
      fontSize={256}
      fill="#FFF"
      letterSpacing={64}
      marginRight={-64}
    />
  </Rect>
</Node>
```
![image](https://user-images.githubusercontent.com/64662184/225357491-287b0436-71b0-4190-811d-c9329449fd6d.png)
