### ISSUE TITLE
Interactive Canvas?

### ISSUE THREAD

**Issue by anthonysapien** [motion-canvas/motion-canvas#550]
**Description**
Could Motion Canvas or a fork be used for interactive documents? I have a challenge at work to show visually how changing input parameters impact outcomes. It would be amazing to integrate storytelling with some interactivity when you reach a specific point in a scene. For example, "What is your budget?" with an input or slider. That could then impact the animation.

**Proposed solution**
Allow some components to respond to input events like entering text or shifting a slider. These inputs could inform signals. Then perhaps another action/button to proceed with the animation. Perhaps the animation could fork to a different scene depending on the input signal values.

**Considered alternatives**
I could build something fully custom in React. :/ 

**Additional context**
I fully understand if this isn't your goal, but I think it could be really powerful for personalized storytelling.

**Comment by cowolff** [comment]
Just as an addition to that: I plan on using motion canvas to create presentations for scientific conferences in the near future. It would be really amazing, if one could use interactive sliders/buttons to change some values "live" during the presentation. That would make it much easier to respond to questions to the presented data.

Like @anthonysapien I totally understand if this feature request is too far off the original idea of motion canvas, but in my opinion, this would make this tool even more attractive to researchers and data scientists.

**Comment by aarthificial** [comment]
We use a pure canvas for rendering - there's no HTML/CSS being used.
This means that a feature like this would require us to implement an entire framework for dealing with event propagation, mouse/keyboard handling, etc. since we can't just place an HTML input on a screen.
Needless to say, this is extremely out of scope for now.

The closest thing to this is #170 which will introduce editable signals. But they will be edited through the editor/presenter interface, it won't be possible to place an input element *inside of* the animation itself.

**Comment by anthonysapien** [comment]
Hi Jacob, for responding and explaining. That makes a lot of sense. I'll see what I can do with controls outside of the animation. Thanks for creating the framework!
