### ISSUE TITLE
Add guides to docs

### ISSUE THREAD

**Issue by aarthificial** [motion-canvas/motion-canvas#7]
**Description**
Current documentation is missing any sort of guides/tutorials.
[typedoc-plugin-pages](https://github.com/KnodesCommunity/typedoc-plugins/tree/main/packages/plugin-pages) can be used to add them to the currently existing API docs. 
Source files would be stored inside of the `docs` directory as markdown files. 
This would make them available through GitHub for people who haven't set up Motion Canvas yet.

**Comment by Jeff0502** [comment]
Hey! 

Thank you for this excellent project.

I am starting off with Motion Canvas, and as I attempt to create my projects, I really struggle to find basic examples of how to create animations.

**For example:**
I would like to animate basic 'flow-in' text. To achieve this, I googled "how to add text to motion canvas project", but I did not find much, except the API documentation. The API docs are great for experienced users, but unfortunately, since certain components inherit from multiple other components it can become tricky to navigate the API docs.

**Why am I writing this?**
It would be great if I could help to contribute to the project by writing basic examples on the documentation, such as "How to add text to Motion Canvas" or "How to fill the background" - maybe these basic examples can even be combined to something like 'How to create _x_ animation from scratch start to finish'. As a programmer I usually boil things to specifics when I use Google, so I would love to help other people quickly discover how to use this project.
