### ISSUE TITLE
`<Latex>` API docs wrongly show example for `<Img>` component

### ISSUE THREAD

**Issue by LorisSigrist** [motion-canvas/motion-canvas#755]
**Description**
The API documentation for the`<Latex>` component (here https://motioncanvas.io/api/2d/components/Latex) show an example for the `<Img>` component instead. It's the same example that is used on the API docs for the `<Img>` component.

<img width="1440" alt="Screenshot 2023-06-29 at 16 39 38" src="https://github.com/motion-canvas/motion-canvas/assets/43482866/03424302-b90c-4c8e-bfba-a08697a8b5f4">

**Comment by WaldemarLehner** [comment]
Oh. It is inheriting the docs from the  `Img` :smile: 

Here is the Img Source File:
https://github.com/motion-canvas/motion-canvas/blob/main/packages/2d/src/components/Img.ts#L37-L67

And I assume `Latex` just takes it from `Img` because it does not define an example / JSDoc itself 
https://github.com/motion-canvas/motion-canvas/blob/main/packages/2d/src/components/Latex.ts#L32

I could fix this. Please assign :)
